version: '3.7'

services:

  todo-frontend:
    container_name: todo-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/Users/imc4k/Documents/TATP_training/my-todo'
      - '/Users/imc4k/Documents/TATP_training/my-todo/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true