export const CREATE_NEW_TODO = 'CREATE_NEW_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const UPDATE_TODO_ITEM = 'UPDATE_TODO_ITEM';
export const SET_TODO_LIST = 'SET_TODO_LIST';
export const SET_LABEL_ADDER_VISIBILITY = 'SET_LABEL_ADDER_VISIBILITY';
export const SET_TARGET_TODO_ITEM = 'SET_TARGET_TODO_ITEM';